name: CI

on: [push, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit on all files
        run: pre-commit run --all-files
        env:
          SKIP: check-untracked-files

  test-unit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-bdd
      - name: install requirements
        run: pip install -r requirements.txt
      - name: python tests
        run: |
          pytest

  test-e2e:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: install python dependencies
        run: |
          python -m pip install --upgrade pip
      - uses: pnpm/action-setup@v4
        with:
          version: 10.14.0
      - name: install thingity
        run: pip install -e .
      - name: install dependencies
        run: sudo apt-get install -y fzf silversearcher-ag ripgrep
      - name: run cli
        run: |
          things-search --noconfig --dry -n headings
          echo "things-search --noconfig -n headings"
          things-search --noconfig -n headings
          echo "things-search --noconfig --dry"
          things-search --noconfig --dry
          echo "things-search --noconfig"
          things-search --noconfig
          echo "Direct rg"
          rg --version
          ls
          ls -R things
          echo "rg basic"
          rg --debug thing .
          echo "rg with glob"
          rg --glob '**/*.md' '' .
          echo "Direct rg full 2"
          rg -i --glob '!archive/' --glob '**/*.md' --no-heading --follow --color never -n -m 1 '' .
          echo "things with filter"
          things --noconfig --test "test thing 2"
          echo "rg bananas with ripgrep backend"
          rg --no-heading --follow --color never bananas .
          echo "todo with filter"
          todo --noconfig --test bananas
        working-directory: test
      - name: pnpm install
        working-directory: test
        run: pnpm i
      - name: test
        working-directory: test
        run: pnpm test
